#!/usr/bin/env bash
# ---------------------
# Global Dependencies
# ---------------------

# tgpt 
# - https://github.com/aandrew-me/tgpt

# OPENAI_API_KEY
# -  this is optional
# -  create this with https://platform.openai.com/account/organization
# ---------------------
AI_MODEL=""
AI_PROVIDER=""
OPENAI_API_KEY=""
USER_INPUT=""

get_config_file_location() {
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    CONFIGURATION_DIRECTORY="$(cd ${SCRIPT_DIR} && cd ../configuration && pwd)"
    echo "${CONFIGURATION_DIRECTORY}/config.sh"
}

initialize_variables_from_configuration_file() {
    CONFIGURATION_FILE="$(get_config_file_location)"
    # This will load in the necessary variables
    # - AI_MODEL
    # - AI_PROVIDER
    # - OPENAI_API_KEY

    source ${CONFIGURATION_FILE}
}

initialize_user_input() {
    echo "Input question"
    read USER_INPUT
}

initialize_variables() {
    initialize_variables_from_configuration_file
    initialize_user_input
}


run_ai() {

    echo "You are asking..."
    echo "${@}"

    tgpt \
        --provider ${AI_PROVIDER} \
        --key "${OPENAI_API_KEY}" \
        --model "${AI_MODEL}" \
        \'"${USER_INPUT}"\'
}

run() {
    initialize_variables
    run_ai
}

run
